// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZxgOUwVVqSM59iJQQ9TXXJdOhosZ8zA',
    appId: '1:84889783474:web:6cc2b0b0ee8c3de06c8dab',
    messagingSenderId: '84889783474',
    projectId: 'deep-focus-d140c',
    authDomain: 'deep-focus-d140c.firebaseapp.com',
    storageBucket: 'deep-focus-d140c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6cnwWAkr4poFx3L1uz6iWP12OpleaTU',
    appId: '1:84889783474:android:3d87d34cee6b2f536c8dab',
    messagingSenderId: '84889783474',
    projectId: 'deep-focus-d140c',
    storageBucket: 'deep-focus-d140c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakd51jtehl1tCn7jamVE-ak_aQB3ClfM',
    appId: '1:84889783474:ios:7604779bb59ad1886c8dab',
    messagingSenderId: '84889783474',
    projectId: 'deep-focus-d140c',
    storageBucket: 'deep-focus-d140c.firebasestorage.app',
    iosBundleId: 'com.example.deepFocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBakd51jtehl1tCn7jamVE-ak_aQB3ClfM',
    appId: '1:84889783474:ios:7604779bb59ad1886c8dab',
    messagingSenderId: '84889783474',
    projectId: 'deep-focus-d140c',
    storageBucket: 'deep-focus-d140c.firebasestorage.app',
    iosBundleId: 'com.example.deepFocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZxgOUwVVqSM59iJQQ9TXXJdOhosZ8zA',
    appId: '1:84889783474:web:d160f68dbd38f2206c8dab',
    messagingSenderId: '84889783474',
    projectId: 'deep-focus-d140c',
    authDomain: 'deep-focus-d140c.firebaseapp.com',
    storageBucket: 'deep-focus-d140c.firebasestorage.app',
  );
}
